server:
  port: 8002

#  servlet:
#    context-path: /

spring:
  security:
    user:
      password: admin
      name: root
  application:
    name: auth
  profiles:
    active: local
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
    #,classpath:/META-INF/resources/webjars/,classpath:/META-INF/resources
  #   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #,file:${web.upload-path},file:${web.vue-path}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #https://blog.csdn.net/zoeou/article/details/78629032

#\u914D\u7F6E\u65E5\u5FD7,\u65E5\u5FD7\u7528xml\u53BB\u914D\u7F6E
log:
  dir: ./log
